services:
  subql-ai:
    # image: subquerynetwork/subql-ai-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7827:7827
    restart: unless-stopped
    volumes:
      - ./subquery-delegator:/app
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      # - -p=/app/index.ts # TODO this doesn't work because dependencies are not copied
      - -p=ipfs://QmRUryPFBzsozSCTLz8P5JDpPUm2zztetqi7v6Lv8j916k
      - -h=http://host.docker.internal:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subql-ai:7827/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  # A simple chat UI
  ui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    restart: always
    depends_on:
      "subql-ai":
        condition: service_healthy
    environment:
      - "OPENAI_API_BASE_URLS=http://subql-ai:7827/v1"
      - "OPENAI_API_KEYS=foobar"
      - "WEBUI_AUTH=false"
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:
