name: Docker Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'


jobs:
  publish-docker:
    name: publish-docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: subquerynetwork/subql-ai-app

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: subquerynetwork
          password: ${{ secrets.SQ_DOCKERHUB_TOKEN }}

      - name: Update package deno.json
        run: jq --arg version "${{ steps.meta.outputs.version }}" '.version = $version' deno.json > tmp.json && mv tmp.json deno.json

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: arm64,amd64
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
